// Карта «Финансы» — воссоздана из реального Атласа метрик (RU, Miro-экспорт).
// Узлы на АВТОРСКИХ координатах (масштаб 0.82).
// P1-фикс (ICP-панель 19_icp_finance_ux): солид-рёбра = ТОЖДЕСТВА (арифметика, оператор term/subtrahend,
// без причинной стрелки); ВЛИЯНИЯ (гипотезы) — отдельный класс с mechanism+flip. Стержень = ствол результата.
import type { Graph } from './types'

export const FINANCE: Graph = {
  nodes: [
    { id: 'sebestoimost_prodazh', ru: 'Себестоимость продаж', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 2, formula: 'Σ прямых затрат на проданное' },
    { id: 'chistaya_pribyl', ru: 'Чистая прибыль', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'more_better', grain: 'период', controllability: 'result', goodhart_risk: 'low', role_default: 'result', tier: 1, formula: 'Операционная прибыль − Налог на прибыль − Обслуживание долга' },
    { id: 'rentabelnost_valovoy_pri', ru: 'Рентабельность валовой прибыли', en: '', section: 'Финансы', quantity_type: 'ratio', additivity: 'int', essence: 'more_better', grain: 'период', controllability: 'semi', goodhart_risk: 'low', role_default: 'diagnostic', tier: 3 },
    { id: 'valovaya_pribyl', ru: 'Валовая прибыль', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'more_better', grain: 'период', controllability: 'result', goodhart_risk: 'low', role_default: 'result', tier: 1, formula: 'Выручка − Себестоимость продаж' },
    { id: 'nalog_na_pribyl', ru: 'Налог на прибыль', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 2 },
    { id: 'rashody_na_ekvayring', ru: 'Расходы на эквайринг', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'rashody_na_logistiku', ru: 'Расходы на логистику', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'marketingovye_rashody', ru: 'Маркетинговые расходы', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'rentabelnost_chistoy_pri', ru: 'Рентабельность чистой прибыли', en: '', section: 'Финансы', quantity_type: 'ratio', additivity: 'int', essence: 'more_better', grain: 'период', controllability: 'semi', goodhart_risk: 'low', role_default: 'diagnostic', tier: 3 },
    { id: 'skidki', ru: 'Скидки', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'result', goodhart_risk: 'low', role_default: 'result', tier: 2 },
    { id: 'vozvraty', ru: 'Возвраты', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'operacionnye_rashody', ru: 'Операционные расходы', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 2, formula: 'Σ операционных статей затрат' },
    { id: 'arenda', ru: 'Аренда', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'it_i_infrastruktura', ru: 'IT и инфраструктура', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'vyruchka', ru: 'Выручка', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'more_better', grain: 'период', controllability: 'result', goodhart_risk: 'low', role_default: 'result', tier: 1, formula: 'Заказы × Средний чек − Скидки − Возвраты' },
    { id: 'sebestoimost_tovara_proi', ru: 'Себестоимость товара / производства', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'fot_proizvodstvennogo_pe', ru: 'ФОТ производственного персонала', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'operacionnaya_pribyl', ru: 'Операционная прибыль', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'more_better', grain: 'период', controllability: 'result', goodhart_risk: 'low', role_default: 'result', tier: 1, formula: 'Валовая прибыль − Операционные расходы' },
    { id: 'rentabelnost_reklamnyh_r', ru: 'Рентабельность рекламных расходов (ROAS)', en: '', section: 'Финансы', quantity_type: 'ratio', additivity: 'int', essence: 'more_better', grain: 'период', controllability: 'semi', goodhart_risk: 'low', role_default: 'diagnostic', tier: 3 },
    { id: 'rentabelnost_investiciy_', ru: 'Рентабельность инвестиций (ROI)', en: '', section: 'Финансы', quantity_type: 'ratio', additivity: 'int', essence: 'more_better', grain: 'период', controllability: 'semi', goodhart_risk: 'low', role_default: 'diagnostic', tier: 3 },
    { id: 'rashody_na_klientskiy_se', ru: 'Расходы на клиентский сервис', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'rashody_na_upakovku', ru: 'Расходы на упаковку', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'rd_rashody', ru: 'R&D расходы', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'obsluzhivanie_dolga', ru: 'Обслуживание долга', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 2 },
    { id: 'rentabelnost_operacionno', ru: 'Рентабельность операционной прибыли', en: '', section: 'Финансы', quantity_type: 'ratio', additivity: 'int', essence: 'more_better', grain: 'период', controllability: 'semi', goodhart_risk: 'low', role_default: 'diagnostic', tier: 3 },
    { id: 'rost_chistoy_pribyli', ru: 'Рост чистой прибыли', en: '', section: 'Финансы', quantity_type: 'percent', additivity: 'int', essence: 'more_better', grain: 'период', controllability: 'semi', goodhart_risk: 'low', role_default: 'diagnostic', tier: 3 },
    { id: 'amortizaciya', ru: 'Амортизация', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
    { id: 'fot_administrativnyy', ru: 'ФОТ административный', en: '', section: 'Финансы', quantity_type: 'money', additivity: 'ext', essence: 'less_better', grain: 'период', controllability: 'lever', goodhart_risk: 'low', role_default: 'cost', tier: 3 },
  ],
  edges: [
    // ── ТОЖДЕСТВА (арифметика P&L): оператор, НЕ причинная стрелка ──
    { source: 'sebestoimost_tovara_proi', target: 'sebestoimost_prodazh', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'fot_proizvodstvennogo_pe', target: 'sebestoimost_prodazh', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'valovaya_pribyl', target: 'operacionnaya_pribyl', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'operacionnaya_pribyl', target: 'chistaya_pribyl', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'skidki', target: 'vyruchka', kind: 'identity', op: 'subtrahend', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'vyruchka', target: 'valovaya_pribyl', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'vozvraty', target: 'vyruchka', kind: 'identity', op: 'subtrahend', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'sebestoimost_prodazh', target: 'valovaya_pribyl', kind: 'identity', op: 'subtrahend', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'nalog_na_pribyl', target: 'chistaya_pribyl', kind: 'identity', op: 'subtrahend', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'operacionnye_rashody', target: 'operacionnaya_pribyl', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'obsluzhivanie_dolga', target: 'chistaya_pribyl', kind: 'identity', op: 'subtrahend', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'rashody_na_logistiku', target: 'sebestoimost_prodazh', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'rashody_na_upakovku', target: 'sebestoimost_prodazh', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'rashody_na_ekvayring', target: 'sebestoimost_prodazh', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'amortizaciya', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'rd_rashody', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'marketingovye_rashody', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'rashody_na_klientskiy_se', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'it_i_infrastruktura', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'fot_administrativnyy', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    { source: 'arenda', target: 'operacionnye_rashody', kind: 'identity', op: 'term', sign: 'n/a', strength: 'strong', confidence: 'high', provenance: 'curated' },
    // ── ВЛИЯНИЯ (гипотезы, требуют проверки на данных): mechanism + flip ──
    { source: 'marketingovye_rashody', target: 'vyruchka', kind: 'influence', sign: '+', mechanism: 'рост охвата и спроса тянет заказы, а с ними выручку', flip: 'до насыщения канала; сверх порога CAC растёт, отдача падает к нулю', strength: 'medium', confidence: 'low', provenance: 'draft' },
    { source: 'skidki', target: 'vyruchka', kind: 'influence', sign: '+', mechanism: 'скидка поднимает конверсию и объём продаж', flip: 'арифметически скидка ВЫЧИТАЕТСЯ из выручки (тождество −); как рычаг растит объём, но сверх порога режет маржу и кэннибализирует', strength: 'medium', confidence: 'low', provenance: 'draft' },
    // ── АССОЦИАЦИИ (диагностика): связано, стрелку не утверждаем ──
    { source: 'valovaya_pribyl', target: 'rentabelnost_valovoy_pri', kind: 'associative', sign: 'n/a', strength: 'medium', confidence: 'low', provenance: 'curated' },
    { source: 'operacionnaya_pribyl', target: 'rentabelnost_operacionno', kind: 'associative', sign: 'n/a', strength: 'medium', confidence: 'low', provenance: 'curated' },
    { source: 'chistaya_pribyl', target: 'rentabelnost_chistoy_pri', kind: 'associative', sign: 'n/a', strength: 'medium', confidence: 'low', provenance: 'curated' },
    { source: 'chistaya_pribyl', target: 'rost_chistoy_pribyli', kind: 'associative', sign: 'n/a', strength: 'medium', confidence: 'low', provenance: 'curated' },
    { source: 'valovaya_pribyl', target: 'rentabelnost_investiciy_', kind: 'associative', sign: 'n/a', strength: 'medium', confidence: 'low', provenance: 'curated' },
    { source: 'vyruchka', target: 'rentabelnost_reklamnyh_r', kind: 'associative', sign: 'n/a', strength: 'medium', confidence: 'low', provenance: 'curated' },
  ],
}

export const FINANCE_POS: Record<string, { x: number; y: number }> = {
  'sebestoimost_prodazh': { x: 423.6, y: 1256.5 },
  'chistaya_pribyl': { x: 818.8, y: 75.6 },
  'rentabelnost_valovoy_pri': { x: 1212.4, y: 1247.0 },
  'valovaya_pribyl': { x: 818.0, y: 1256.5 },
  'nalog_na_pribyl': { x: 423.6, y: 49.4 },
  'rashody_na_ekvayring': { x: 40.0, y: 1038.8 },
  'rashody_na_logistiku': { x: 40.0, y: 1256.5 },
  'marketingovye_rashody': { x: 40.0, y: 424.8 },
  'rentabelnost_chistoy_pri': { x: 1212.4, y: 40.0 },
  'skidki': { x: 392.2, y: 1801.6 },
  'vozvraty': { x: 392.2, y: 1702.0 },
  'operacionnye_rashody': { x: 423.6, y: 525.6 },
  'arenda': { x: 40.0, y: 809.6 },
  'it_i_infrastruktura': { x: 40.0, y: 626.8 },
  'vyruchka': { x: 818.0, y: 1801.6 },
  'sebestoimost_tovara_proi': { x: 40.0, y: 1365.4 },
  'fot_proizvodstvennogo_pe': { x: 40.0, y: 1492.8 },
  'operacionnaya_pribyl': { x: 818.8, y: 525.6 },
  'rentabelnost_reklamnyh_r': { x: 1212.4, y: 1782.7 },
  'rentabelnost_investiciy_': { x: 1212.4, y: 1365.4 },
  'rashody_na_klientskiy_se': { x: 40.0, y: 516.4 },
  'rashody_na_upakovku': { x: 40.0, y: 1147.7 },
  'rd_rashody': { x: 40.0, y: 333.2 },
  'obsluzhivanie_dolga': { x: 423.6, y: 140.4 },
  'rentabelnost_operacionno': { x: 1212.4, y: 516.2 },
  'rost_chistoy_pribyli': { x: 1212.4, y: 162.1 },
  'amortizaciya': { x: 40.0, y: 241.6 },
  'fot_administrativnyy': { x: 40.0, y: 718.4 },
}
